Join table for visits
Jawad-Nazari/Vet-clinic pull request #4
Opened 2023-06-15 20:39 UTC by Jawad-Nazari

### In this PR, I did the following:

-  Created a table named vets.
- Added many-to-many relationship between the species and vets tables .
- Added many-to-many relationship between the animals and vets tables .
- Inserted data to visits, vets, and specializations as per project requirements.
Who was the last animal seen by William Tatcher?
![q1](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/4212cb84-69fa-4dc2-ac91-c35370e6460f)

How many different animals did Stephanie Mendez see?
![q2](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/e68229ee-4960-46d4-86dd-99e7f4f0db6e)

List all vets and their specialties, including vets with no specialties.
![q3](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/c4cde308-45ad-47df-ac9e-fe3e689629b5)

List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
![q4](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/8d36d901-ddd3-42b9-b686-12b236bd2e8e)

What animal has the most visits to vets?
![q5](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/5a3adc37-9742-4d2a-ac4b-ae783bdfc4ab)

Who was Maisy Smith's first visit?
![q6](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/df85964e-65f5-4087-8715-a8e6c82c50e1)

Details for most recent visit: animal information, vet information, and date of visit.
![q7](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/6fc28134-8969-4c33-84a3-aca186159b12)

How many visits were with a vet that did not specialize in that animal's species?
![q8](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/dad50dee-76a3-4e79-aea2-49c314718e0e)

What specialty should Maisy Smith consider getting? Look for the species she gets the most.
![q9](https://github.com/Jawad-Nazari/Vet-clinic/assets/115032263/88361368-a3b4-4180-8297-f399b9646853)

2023-06-15 21:47 UTC, laiifuu requested changes
# STATUS: CHANGES REQUIRED :recycle: 

## Hi @Jawad-Nazari :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://github.com/Jawad-Nazari/Vet-clinic/assets/93520178/14461a7b-37c3-4fcb-9755-cffeb5309fcb)


## Highlights
- [x] Organized queries :heavy_check_mark: 
- [x] Great take on data insertion :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 21:47 UTC, laiifuu commented on queries.sql
> +
The answer for this query should be 12 visits, which include all visits by Maisy Smith, 2 visits by William Tatcher and 1 visit by Jack Harkness. And your screenshot shows 7.

2023-06-15 21:47 UTC, laiifuu commented on queries.sql
> +GROUP BY species.name ORDER BY COUNT(*) DESC LIMIT 1;
The response for this query should be `Digimon` as she has 6 visits by pets of this type. But your screenshot shows `0 rows`.

2023-06-16 04:34 UTC, Jawad-Nazari commented on queries.sql
> +
Hi @laiifuu ,
Thanks for reviewing my code. I have updated my query to get the correct result. 🙏

2023-06-16 04:35 UTC, Jawad-Nazari commented on queries.sql
> +GROUP BY species.name ORDER BY COUNT(*) DESC LIMIT 1;
Hi @laiifuu ,

Thanks for reviewing my code. I have updated my query to reflect the correct answer. 🙏

2023-06-16 04:50 UTC, Deepakdanger approved these changes
Hi @Jawad-Nazari , 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 06:46 UTC, merged